### ISSUE TITLE
Connection caching

### ISSUE THREAD

**Issue by Triangle333** [PonomarevDmitry/CrmDeveloperHelper#2]
Every action creates a new connection from the beginning, this takes considerable time with Cloud environments. Please implement connection caching, keep it open for 15 mins at least.

**Comment by PonomarevDmitry** [comment]
Hi.

Sorry, I didn’t notice the appearance of new issues.

Thank you for your remark.

Yes, I realized that a connection takes a lot of time each time and it’s better to just keep some pool of open connections.

I will try to realize this soon.

--
Best regards

**Comment by PonomarevDmitry** [comment]
Hi.

I implement connection pool in version 1.0.0.669.

Please report connection pool bugs.

--
Best regards
