### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Triangle333** [PonomarevDmitry/CrmDeveloperHelper#3]
When opening some heavy browser window (like Plugin Tree) there is some logging in Output but nothing else happens. Window can appear after 1-3 minutes and this is counter-intuitive.

Please show the window immediately and display some data loading progress bar or wait icon/message.

Data loading time is also suspicious because we don't experience such timeouts when using web UI or PluginRegistration Tool...

**Comment by PonomarevDmitry** [comment]
Hi.

Sorry, I didn’t notice the appearance of new issues.

Thank you for your remark.

I will try to optimize the Data loading time from the Dynamics CRM.

I will also add log entries to Output Window for received data.

--
Best regards

**Comment by PonomarevDmitry** [comment]
Hi.

I did some optimization and added messages to the output window.

--
Best regards
