### ISSUE TITLE
Error in WebResource Project on every Menu Command

### ISSUE THREAD

**Issue by AlGu1** [PonomarevDmitry/CrmDeveloperHelper#4]
Hi,
in the current Version (1.0.0.513) we have the folling Error on every Operation in context menu:

`Exception.Message - Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Exception.HResult - -2147467261
Nav.Common.VSPackages.CrmDeveloperHelper
   bei Nav.Common.VSPackages.CrmDeveloperHelper.Helpers.DTEHelper.<FillHashSubProjectItems>d__226.MoveNext() in C:\GitHub\CrmDeveloperHelper\CrmDeveloperHelper\Helpers\DTEHelper.SelectedElements.cs:Zeile 283.
   bei Nav.Common.VSPackages.CrmDeveloperHelper.Helpers.DTEHelper.<GetSelectedFilesInSolutionExplorer>d__225.MoveNext() in C:\GitHub\CrmDeveloperHelper\CrmDeveloperHelper\Helpers\DTEHelper.SelectedElements.cs:Zeile 250.
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Nav.Common.VSPackages.CrmDeveloperHelper.Commands.WebResources.FolderWebResourceLinkClearCommand.CommandAction(DTEHelper helper) in C:\GitHub\CrmDeveloperHelper\CrmDeveloperHelper\Commands\WebResources\FolderWebResourceLinkClearCommand.cs:Zeile 23.
   bei Nav.Common.VSPackages.CrmDeveloperHelper.Commands.AbstractCommand.menuItemCallback(Object sender, EventArgs e) in C:\GitHub\CrmDeveloperHelper\CrmDeveloperHelper\Commands\AbstractCommand.cs:Zeile 64.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Nav.Common.VSPackages.CrmDeveloperHelper.Helpers.DTEHelper.<FillHashSubProjectItems>d__226.MoveNext() in C:\GitHub\CrmDeveloperHelper\CrmDeveloperHelper\Helpers\DTEHelper.SelectedElements.cs:Zeile 283.
   bei Nav.Common.VSPackages.CrmDeveloperHelper.Helpers.DTEHelper.<GetSelectedFilesInSolutionExplorer>d__225.MoveNext() in C:\GitHub\CrmDeveloperHelper\CrmDeveloperHelper\Helpers\DTEHelper.SelectedElements.cs:Zeile 250.
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Nav.Common.VSPackages.CrmDeveloperHelper.Commands.WebResources.FolderWebResourceLinkClearCommand.CommandAction(DTEHelper helper) in C:\GitHub\CrmDeveloperHelper\CrmDeveloperHelper\Commands\WebResources\FolderWebResourceLinkClearCommand.cs:Zeile 23.
   bei Nav.Common.VSPackages.CrmDeveloperHelper.Commands.AbstractCommand.menuItemCallback(Object sender, EventArgs e) in C:\GitHub\CrmDeveloperHelper\CrmDeveloperHelper\Commands\AbstractCommand.cs:Zeile 64.`
I think the new variable "saveIfNeeded" is null, because the calling function dose not post it.

Please fix it or is it not a bug? :-)

Thanks and best regards

**Comment by AlGu1** [comment]
If i understand the Code, i think the problem is in Line 210 of File "https://github.com/PonomarevDmitry/CrmDeveloperHelper/blob/master/CrmDeveloperHelper/Helpers/DTEHelper.SelectedElements.cs"
Because the function "GetSelectedFilesInSolutionExplorer" has now 4 params and the "saveIfNeeded" is in Line 237 NULL, the line 210 call the method with 3 params.

Can you please check this :-)
thanks AlGu

**Comment by PonomarevDmitry** [comment]
Hi.

Sorry, I didn’t notice the appearance of new issues.

I discovered this bug myself and quickly fixed it.

Commit:
https://github.com/PonomarevDmitry/CrmDeveloperHelper/commit/8848a7692a40bda6e830a12bb4e2db610fa444db

Thank you for your remark.

--
Best regards
